Repository ChuckerTeam/chucker, pull requests merged in 2018-11, with the labels that each got.

#1 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#3 Rename every Chucky ref to Chucker
  CHANGELOG.md
  README.md
  gradle.properties
  gradle/gradle-mvn-push.gradle
  library/src/main/res/values/strings.xml
  sample/src/main/res/values/strings.xml
Labels: enhancement

#7 Fix Issue #5 encoding not supported
  build.gradle
  library/build.gradle
  library/src/main/java/com/readystatesoftware/chuck/internal/support/IOUtils.java
  library/src/test/java/com/readystatesoftware/chuck/internal/support/IOUtilsTest.kt
Labels: bug

#6 Issue #43 Ask for confirmation when delete history
  library/src/main/java/com/readystatesoftware/chuck/internal/ui/error/ErrorListFragment.java
  library/src/main/java/com/readystatesoftware/chuck/internal/ui/transaction/TransactionListFragment.java
  library/src/main/res/values/strings.xml
Labels: enhancement

#16 [TECH] Configure a debug keystore
  sample/build.gradle
  sample/debug.keystore
Labels: enhancement

#18 Added Snapshots section to Readme
  README.md
Labels: infra

#20 Fix #19 Change DB version number 3->4
  library/src/main/java/com/readystatesoftware/chuck/internal/data/ChuckDbOpenHelper.java
Labels: bug

#17 Highlight search result in response tab
  build.gradle
  gradle/gradle-mvn-push.gradle
  library-no-op/build.gradle
  library/build.gradle
  library/src/main/java/com/readystatesoftware/chuck/internal/support/SearchHighlightUtil.kt
  library/src/main/java/com/readystatesoftware/chuck/internal/ui/transaction/TransactionActivity.java
  library/src/main/java/com/readystatesoftware/chuck/internal/ui/transaction/TransactionPayloadFragment.java
  library/src/main/java/com/readystatesoftware/chuck/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/menu/chuck_transaction.xml
  sample/src/main/AndroidManifest.xml
Labels: enhancement

#12 Prepare 2.1.0
  gradle.properties
Labels: infra

#25 Added Project Icon to Readme
  README.md
Labels: enhancement

#22 Modernize the project icon
  library/src/main/java/com/readystatesoftware/chuck/internal/support/NotificationHelper.java
  library/src/main/res/drawable-hdpi/chucker_ic_notification.png
  library/src/main/res/drawable-mdpi/chucker_ic_notification.png
  library/src/main/res/drawable-xhdpi/chucker_ic_notification.png
  library/src/main/res/drawable-xxhdpi/chucker_ic_notification.png
  library/src/main/res/drawable-xxxhdpi/chucker_ic_notification.png
  library/src/main/res/drawable/chuck_ic_notification_white_24dp.xml
  sample/src/main/ic_launcher-web.png
  sample/src/main/res/drawable/ic_launcher_foreground.xml
  sample/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  sample/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  sample/src/main/res/mipmap-hdpi/ic_launcher.png
  sample/src/main/res/mipmap-hdpi/ic_launcher_round.png
  sample/src/main/res/mipmap-mdpi/ic_launcher.png
  sample/src/main/res/mipmap-mdpi/ic_launcher_round.png
  sample/src/main/res/mipmap-xhdpi/ic_launcher.png
  sample/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  sample/src/main/res/mipmap-xxhdpi/ic_launcher.png
  sample/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  sample/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  sample/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  sample/src/main/res/values/ic_launcher_background.xml
Labels: enhancement
