Repository ChuckerTeam/chucker, pull requests merged in 2019-09, with the labels that each got.

#107 Detekt to 1.0.1
  build.gradle
  gradle/kotlin-static-analysis.gradle
  library-no-op/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
  library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
  library-no-op/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt
Labels: infra

#108 Kotlinify JsonConverter
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.java
  library/src/main/java/com/chuckerteam/chucker/internal/support/JsonConverter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/JsonConvertor.java
  library/src/test/java/com/chuckerteam/chucker/internal/support/JsonConverterTest.kt
Labels: enhancement

#109 Kotlinify ChuckerCrashHandler
  library/src/main/java/com/chuckerteam/chucker/internal/support/ChuckerCrashHandler.java
  library/src/main/java/com/chuckerteam/chucker/internal/support/ChuckerCrashHandler.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/ChuckerCrashHandlerTest.kt
Labels: enhancement

#111 Removing SimpleOnPageChangedListener
  library/src/main/java/com/chuckerteam/chucker/internal/support/SimpleOnPageChangedListener.java
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.java
Labels: enhancement

#112 Kotlinify ClearDatabaseService
  library/src/main/AndroidManifest.xml
  library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ClearTransactionsService.java
  library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.java
Labels: enhancement

#114 Kotlinify IOUtils
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.java
  library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
Labels: enhancement

#118 Update the request/response body to use a monospace font
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
Labels: enhancement

#119 Display explanation text on tabs if empty
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.java
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.java
  library/src/main/res/layout/chucker_fragment_error_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_list.xml
  library/src/main/res/values/strings.xml
Labels: enhancement

#121 Force all layouts to be LTR
  library/src/main/res/layout/chucker_activity_error.xml
  library/src/main/res/layout/chucker_activity_main.xml
  library/src/main/res/layout/chucker_activity_transaction.xml
  library/src/main/res/layout/chucker_fragment_error_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_overview.xml
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/main/res/layout/chucker_list_item_error.xml
  library/src/main/res/layout/chucker_list_item_transaction.xml
Labels: bug
