Repository ChuckerTeam/chucker, pull requests merged in 2019-12, with the labels that each got.

#160 Add date formatting for requestDate and responseDate
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
Labels: enhancement

#162 Update/components versions
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  library-no-op/build.gradle
  library/build.gradle
  sample/build.gradle
Labels: infra

#165 Close the native source.
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
Labels: bug

#170 Replace sample gif for throwables
  assets/chucker-error.gif
Labels: enhancement

#167 Fix issue with LinearLayoutManager after code minification
  library/proguard-rules.pro
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/res/layout/chucker_fragment_error_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_list.xml
Labels: bug

#146 Pass the -module-name Kotlin Compiler flag
  library-no-op/build.gradle
  library/build.gradle
Labels: bug
