Repository ChuckerTeam/chucker, pull requests merged in 2019-08, with the labels that each got.

#75 Fix application name retrieval.
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/MainActivity.java
Labels: bug

#72 Fetch payload in AsyncTask
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: bug

#76 Prepare 3.0.0-beta1
  gradle.properties
Labels: infra

#77 Fix image being loaded twice for request and response
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: bug

#81 Fix for null values being omitted in the parsed body
  library/src/main/java/com/chuckerteam/chucker/api/internal/support/JsonConvertor.java
  library/src/test/java/com/chuckerteam/chucker/api/internal/support/FormatUtilsTest.kt
Labels: bug

#87 Improving counting of seen transactions in notification message
  library/src/main/java/com/chuckerteam/chucker/api/internal/support/NotificationHelper.java
Labels: bug

#79 Prepare 3.0.0 stable
  gradle.properties
Labels: infra

#89 AndroidX Migration
  build.gradle
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/entity/HttpTransactionTuple.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/entity/RecordedThrowable.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/entity/RecordedThrowableTuple.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/repository/HttpTransactionDatabaseRepository.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/repository/HttpTransactionRepository.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/repository/RecordedThrowableDatabaseRepository.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/repository/RecordedThrowableRepository.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/room/ChuckerDatabase.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/room/HttpTransactionDao.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/room/RecordedThrowableDao.kt
  library/src/main/java/com/chuckerteam/chucker/api/internal/support/ClearTransactionsService.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/support/NotificationHelper.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/support/SimpleOnPageChangedListener.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/BaseChuckerActivity.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/HomePageAdapter.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/MainActivity.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/error/ErrorActivity.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/error/ErrorAdapter.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/error/ErrorListFragment.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionActivity.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionAdapter.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionListFragment.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionOverviewFragment.java
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/layout/chucker_activity_error.xml
  library/src/main/res/layout/chucker_activity_main.xml
  library/src/main/res/layout/chucker_activity_transaction.xml
  library/src/main/res/layout/chucker_fragment_error_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_overview.xml
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/main/res/layout/chucker_list_item_transaction.xml
  library/src/main/res/menu/chucker_transaction.xml
  library/src/main/res/menu/chucker_transactions_list.xml
  sample/build.gradle
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/SampleApplication.java
Labels: enhancement

#95 Gradle to 5.6
  gradle/wrapper/gradle-wrapper.properties
Labels: infra

#97 Prepare 3.0.1 stable
  CHANGELOG.md
  README.md
  gradle.properties
Labels: infra

#98 Add search button on request tab
  library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: enhancement

#103 Fix content type for response formatting
  library/src/main/java/com/chuckerteam/chucker/api/internal/data/entity/HttpTransaction.kt
Labels: bug

#104 Kotlin to 1.3.50
  build.gradle
Labels: infra
