Repository ChuckerTeam/chucker, pull requests merged in 2019-10, with the labels that each got.

#125 Kotlinify Chucker sample app
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinApi.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/SampleApiService.java
Labels: enhancement

#123 Kotlinify classes in .internal.ui.error package
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.java
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.java
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorAdapter.java
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.java
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.kt
Labels: Hacktoberfest, enhancement

#133 Updating Detekt to 1.1.0
  build.gradle
  gradle/kotlin-static-analysis.gradle
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: infra

#144 Fix notification importance for Android Q
  library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.java
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPagerAdapter.kt
Labels: enhancement

#147 Remove unused variable in ClearDatabaseService
  library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt
Labels: bug

#148 Another fix for notifications in Q
  library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt
Labels: enhancement

#149 Update/share util
  library/src/main/java/com/chuckerteam/chucker/internal/ui/BaseChuckerActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/res/values/strings.xml
Labels: enhancement
