Repository ChuckerTeam/chucker, pull requests merged in 2020-03, with the labels that each got.

#253 Switch views to ViewBinding
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/layout/chucker_activity_error.xml
  library/src/main/res/layout/chucker_activity_main.xml
  library/src/main/res/layout/chucker_activity_transaction.xml
  library/src/main/res/layout/chucker_fragment_error_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_overview.xml
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/main/res/layout/chucker_list_item_error.xml
  library/src/main/res/layout/chucker_list_item_transaction.xml
  library/src/main/res/layout/chucker_transaction_item_body_line.xml
  library/src/main/res/layout/chucker_transaction_item_headers.xml
  library/src/main/res/layout/chucker_transaction_item_image.xml
  library/src/main/res/values/strings.xml
Labels: enhancement

#258 Feature/truth
  build.gradle
  library/build.gradle
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormattedUrlTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/JsonConverterTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataCombineLatestTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataDistinctUntilChangedTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt
Labels: enhancement

#257 Add missing ThrowableViewModel
  library/src/main/AndroidManifest.xml
  library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/HomePageAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableViewModel.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/res/layout/chucker_activity_throwable.xml
  library/src/main/res/layout/chucker_fragment_throwable_list.xml
  library/src/main/res/layout/chucker_list_item_throwable.xml
  library/src/main/res/menu/chucker_throwable.xml
  library/src/main/res/menu/chucker_throwables_list.xml
  library/src/main/res/values/strings.xml
Labels: enhancement

#262 Migrating from Travis to GH Actions
  .github/workflows/pre-merge.yaml
  .travis.yml
Labels: infra

#277 Margin fix for transaction payload
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/main/res/layout/chucker_transaction_item_headers.xml
Labels: bug

#275 UX improvements
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/ProtocolResources.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt
  library/src/main/res/drawable/chucker_ic_http.xml
  library/src/main/res/drawable/chucker_ic_https.xml
  library/src/main/res/layout/chucker_list_item_transaction.xml
  library/src/main/res/values-night/colors.xml
  library/src/main/res/values/colors.xml
Labels: enhancement

#281 Add tests to format utils
  library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsSharedTextTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt
Labels: enhancement

#270 Migrate to Kotlin Coroutines
  build.gradle
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
  library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionRepository.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RecordedThrowableDatabaseRepository.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RecordedThrowableRepository.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/room/RecordedThrowableDao.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: enhancement
