Repository ChuckerTeam/chucker, pull requests merged in 2020-04, with the labels that each got.

#297 Optimize RecyclerView items
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: enhancement

#309 Dialogs update
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/res/layout/chucker_activity_throwable.xml
  library/src/main/res/layout/chucker_activity_transaction.xml
  library/src/main/res/values/styles.xml
Labels: enhancement

#308 Sample UI updates
  sample/src/main/ic_launcher-web.png
  sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt
  sample/src/main/res/layout/activity_main_sample.xml
  sample/src/main/res/mipmap-mdpi/ic_launcher.png
  sample/src/main/res/mipmap-mdpi/ic_launcher_round.png
  sample/src/main/res/values-night/colors.xml
  sample/src/main/res/values/colors.xml
  sample/src/main/res/values/strings.xml
  sample/src/main/res/values/styles.xml
Labels: enhancement

#315 Add description for empty body items during export
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
  library/src/main/res/values/strings.xml
  library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsSharedTextTest.kt
Labels: enhancement

#312 Limit max lines for transaction list item path and host
  library/src/main/res/layout/chucker_list_item_transaction.xml
  library/src/main/res/values/styles.xml
Labels: enhancement

#314 Fix overlapping texts on Overview tab
  library/src/main/res/layout/chucker_fragment_transaction_overview.xml
Labels: bug

#325 Empty state for payloads
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/drawable/chucker_empty_payload.xml
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/main/res/values/strings.xml
Labels: enhancement

#327 Split the CI steps between build and check
  .github/workflows/pre-merge.yaml
Labels: infra

#305 Ability to export the list of transactions
  library/src/main/AndroidManifest.xml
  library/src/main/java/com/chuckerteam/chucker/internal/data/model/DialogData.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionRepository.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/AndroidCacheFileFactory.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ContextExt.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/FileFactory.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ShareUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/res/menu/chucker_transactions_list.xml
  library/src/main/res/values/strings.xml
  library/src/main/res/xml/provider_paths.xml
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/ShareUtilsTest.kt
Labels: enhancement

#323 Format URL encoded forms
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/JsonConverter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionViewModel.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinApi.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
Labels: enhancement

#330 Setup a Kotlin version matrix on GH Actions
  .github/workflows/pre-merge.yaml
  build.gradle
Labels: infra

#333 Add resource prefix enforcement
  library/build.gradle
  library/src/main/AndroidManifest.xml
  library/src/main/res/xml/chucker_provider_paths.xml
Labels: enhancement

#334 Adding util GH actions
  .github/workflows/auto_rebase.yaml
  .github/workflows/auto_revert.yaml
Labels: infra
