Repository ChuckerTeam/chucker, pull requests merged in 2020-10, with the labels that each got.

#463 Update team members list
  README.md
Labels: documentation

#465 Fix leaking MainActivity
  build.gradle
  library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProvider.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/BaseChuckerActivity.kt
Labels: bug, enhancement

#467 Bump target and compile SDK to 30
  build.gradle
  library/src/main/AndroidManifest.xml
Labels: enhancement

#471 Update/workflows
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/pre-merge.yaml
Labels: infra

#473 Add Unreleased section to changelog
  CHANGELOG.md
Labels: documentation

#477 Fix compiler flag for explicit API mode
  library/build.gradle
  library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
  library/src/test/java/com/chuckerteam/chucker/TestUtils.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTupleTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProviderTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDaoTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/ChuckerCrashHandlerTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/DepletingSourceTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormattedUrlTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/JsonConverterTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataCombineLatestTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataDistinctUntilChangedTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/ReportingSinkTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionCurlCommandSharableTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionDetailsSharableTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionListDetailsSharableTest.kt
Labels: enhancement

#481 Remove kotlin-android-extensions
  CHANGELOG.md
  library/build.gradle
  sample/build.gradle
  sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt
Labels: bug, enhancement

#482 Gradle to 6.7
  gradle/wrapper/gradle-wrapper.properties
Labels: infra
