Repository ChuckerTeam/chucker, pull requests merged in 2020-02, with the labels that each got.

#222 Fix clear action crash when application is dead
  library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt
Labels: bug

#221 Fix for crash on Save transaction action
  library/src/main/java/com/chuckerteam/chucker/internal/ui/BaseChuckerActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/values/strings.xml
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
Labels: bug

#223 Fix for NPE in NotificationHelper
  library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt
Labels: bug

#220 ViewModel refactoring
  build.gradle
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/internal/support/LiveDataUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionViewModel.kt
Labels: enhancement

#238 Switch to platform defined HTTP code constants
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt
Labels: enhancement

#237 Add instruction for checkbox selection
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#240 Fix HttpHeader serialization when obfuscation is enabled
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpHeader.kt
Labels: bug

#245 Add Action to validate the Gradle Wrapper
  .github/workflows/gradle-wrapper-validation.yml
Labels: infra

#247 Gradle to 6.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: infra

#208 RTL Support
  build.gradle
  gradle.properties
  library/src/main/AndroidManifest.xml
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/drawable/chucker_ic_https_primary.xml
  library/src/main/res/layout/chucker_activity_error.xml
  library/src/main/res/layout/chucker_activity_main.xml
  library/src/main/res/layout/chucker_activity_transaction.xml
  library/src/main/res/layout/chucker_fragment_error_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_list.xml
  library/src/main/res/layout/chucker_fragment_transaction_overview.xml
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/main/res/layout/chucker_list_item_error.xml
  library/src/main/res/layout/chucker_list_item_transaction.xml
  library/src/main/res/layout/chucker_transaction_item_body_line.xml
  library/src/main/res/layout/chucker_transaction_item_headers.xml
  library/src/main/res/layout/chucker_transaction_item_image.xml
  library/src/main/res/values-v21/styles.xml
  library/src/main/res/values/styles.xml
  sample/src/main/AndroidManifest.xml
Labels: enhancement

#252 Feature/tls info
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt
  library/src/main/res/layout/chucker_fragment_transaction_overview.xml
  library/src/main/res/values/strings.xml
Labels: enhancement
