Repository ChuckerTeam/chucker, pull requests merged in 2020-11, with the labels that each got.

#488 Fix for not closed GzipSource
  library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinApi.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt
Labels: bug

#491 Use builder pattern for ChuckerInterceptor in a backwards compatible way
  CHANGELOG.md
  README.md
  library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
Labels: enhancement

#483 Remove deprecated constructor and use exposed builder pattern
  CHANGELOG.md
  library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
Labels: enhancement

#500 Update OkHttp and bump min SDK to 21
  .github/dependabot.yml
  CHANGELOG.md
  README.md
  build.gradle
  library-no-op/build.gradle
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTuple.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/DepletingSource.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormattedUrl.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ReportingSink.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/Sharable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/main/res/layout/chucker_list_item_transaction.xml
  library/src/main/res/layout/chucker_transaction_item_body_line.xml
  library/src/main/res/values-v21/styles.xml
  library/src/main/res/values/styles.xml
  library/src/test/java/com/chuckerteam/chucker/TestUtils.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/data/entity/TransactionTestUtils.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/DepletingSourceTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormattedUrlTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/ReportingSinkTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt
  sample/build.gradle
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
Labels: dependencies, infra

#503 Remove TransactionListFragment
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/res/layout/chucker_activity_main.xml
  library/src/main/res/layout/chucker_fragment_transaction_list.xml
Labels: enhancement

#511 Fix broken lint and add it to GH Actions
  .github/workflows/pre-merge.yaml
  sample/build.gradle
  sample/src/debug/AndroidManifest.xml
  sample/src/main/res/values/dimens.xml
  sample/src/main/res/values/strings.xml
Labels: infra

#509 Add binary-compatibility-validator to Chucker
  .github/workflows/pre-merge.yaml
  build.gradle
  library-no-op/api/library-no-op.api
  library/api/library.api
Labels: infra
