Repository ChuckerTeam/chucker, pull requests merged in 2020-09, with the labels that each got.

#450 Fix classes visibility
  library/src/main/java/com/chuckerteam/chucker/internal/support/ChuckerFileProvider.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/ProtocolResources.kt
Labels: documentation

#451 Enable transaction file sharing
  library/src/main/java/com/chuckerteam/chucker/internal/support/Sharable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ShareUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/TransactionCurlCommandSharable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/TransactionDetailsSharable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/TransactionListDetailsSharable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/res/menu/chucker_transaction.xml
  library/src/main/res/values/strings.xml
  library/src/test/java/com/chuckerteam/chucker/internal/support/ShareUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionCurlCommandSharableTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionDetailsSharableTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionListDetailsSharableTest.kt
Labels: enhancement

#453 Gradle to 6.6.1
  gradle/wrapper/gradle-wrapper.properties
Labels: infra

#454 Kotlin to 1.4.10
  build.gradle
Labels: dependencies

#457 Update Ktlint and Detekt
  build.gradle
Labels: dependencies
