Repository ChuckerTeam/chucker, pull requests merged in 2020-07, with the labels that each got.

#369 Update work with Gradle cache
  .github/workflows/pre-merge.yaml
Labels: infra

#371 Add Dependabot
  .github/dependabot.yml
Labels: infra

#372 Fixes for Dependabot config
  .github/dependabot.yml
Labels: infra

#382 Add Retrofit to ignored list by Dependabot
  .github/dependabot.yml
Labels: infra

#368 Refactor viewmodels initialization to survive process death
  build.gradle
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableViewModel.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionViewModel.kt
Labels: bug

#383 Refactor/change scope
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: enhancement

#386 Kotlin variant in pre-merge to 1.4-M3
  .github/workflows/pre-merge.yaml
Labels: infra

#396 Do not fail requests when side channel file cannot be used
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt
Labels: bug

#400 Minor improvement for transaction saving
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/values/strings.xml
Labels: enhancement
