Repository ChuckerTeam/chucker, pull requests merged in 2020-01, with the labels that each got.

#171 Fix "null" prefix in POM name
  gradle/gradle-mvn-push.gradle
Labels: infra

#169 Minor code cleanup
  library-no-op/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
  library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTuple.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProvider.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt
Labels: enhancement

#138 Add an option to save the request or response body
  detekt-config.yml
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/drawable/chucker_ic_save_white_24dp.xml
  library/src/main/res/menu/chucker_transaction.xml
  library/src/main/res/values/strings.xml
Labels: enhancement

#176 Bump KtLint to 0.36.0
  gradle/kotlin-static-analysis.gradle
  library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/RecordedThrowable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/ChuckerCrashHandlerTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt
Labels: infra

#120 Kotlinify FormatUtils
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.java
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/JsonConverter.kt
Labels: enhancement

#172 Fixing handling of big body payloads
  library/src/main/java/com/chuckerteam/chucker/internal/support/SearchHighlightUtil.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/main/res/layout/chucker_transaction_item_body_line.xml
  library/src/main/res/layout/chucker_transaction_item_headers.xml
  library/src/main/res/layout/chucker_transaction_item_image.xml
  library/src/main/res/values/dimens.xml
  library/src/main/res/values/strings.xml
Labels: bug, enhancement

#186 Fix for wrong class used for extending in ErrorActivity
  library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt
Labels: enhancement

#198 Clone the Response Buffer rather than using it directly
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
Labels: bug

#201 Fix for XML parsing
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
Labels: bug

#206 Fix for Empty Response Body and 0 Content Lenght
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
Labels: bug

#210 Fix for redundant toolbar collapsing
  library/src/main/res/layout/chucker_activity_transaction.xml
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
Labels: enhancement

#214 Fix for curl command
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
Labels: bug

#219 Fix R8 minification crash on TransactionViewModel creation.
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionViewModel.kt
Labels: bug
