Repository ChuckerTeam/chucker, pull requests merged in 2021-01, with the labels that each got.

#526 Centralise all logging in Chucker
  library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/DepletingSource.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/FileFactory.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/Logger.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/Sharable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/test/java/com/chuckerteam/chucker/NoLoggerRule.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/DepletingSourceTest.kt
Labels: enhancement

#533 Update Ktlint to 0.40.0
  build.gradle
  library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
  library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
Labels: dependencies

#537 Update Gradle wrapper to 6.8.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#538 Fix setting request body plain text in transaction
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
Labels: bug

#541 Auto cancel workflow when new push happens
  .github/workflows/pre-merge.yaml
  .github/workflows/publish-snapshot.yaml
Labels: enhancement, github_actions, infra
