Repository ChuckerTeam/chucker, pull requests merged in 2021-02, with the labels that each got.

#549 Update Material to 1.3.0, switch to new CircularProgressIndicator
  build.gradle
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
Labels: dependencies

#545 Redact request headers in case of HTTP failures
  CHANGELOG.md
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/RequestProcessor.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
Labels: bug

#544 Do not process one shot and duplex request bodies
  CHANGELOG.md
  library/src/main/java/com/chuckerteam/chucker/internal/support/RequestProcessor.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinApi.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
Labels: bug

#558 Disable lint check for dependency versions
  library/build.gradle
Labels: enhancement

#557 Update Lifecycle to 2.3.0
  build.gradle
Labels: dependencies

#556 Switch to Activity Result API
  build.gradle
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: dependencies, enhancement

#555 Custom body decoding
  CHANGELOG.md
  README.md
  build.gradle
  gradle/kotlin-static-analysis.gradle
  library-no-op/api/library-no-op.api
  library-no-op/src/main/java/com/chuckerteam/chucker/api/BodyDecoder.kt
  library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/api/library.api
  library/src/main/java/com/chuckerteam/chucker/api/BodyDecoder.kt
  library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/Logger.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/OkioUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/PlainTextDecoder.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/RequestProcessor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ResponseProcessor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/TransactionDetailsSharable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorDecodingTest.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/DepletingSourceTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/LimitingSourceTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataCombineLatestTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataDistinctUntilChangedTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/ReportingSinkTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionCurlCommandSharableTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionDetailsSharableTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionListDetailsSharableTest.kt
  library/src/test/java/com/chuckerteam/chucker/util/ChuckerInterceptorDelegate.kt
  library/src/test/java/com/chuckerteam/chucker/util/ClientFactory.kt
  library/src/test/java/com/chuckerteam/chucker/util/NoLoggerRule.kt
  library/src/test/java/com/chuckerteam/chucker/util/TestTransactionFactory.kt
  library/src/test/java/com/chuckerteam/chucker/util/TestUtils.kt
  sample/build.gradle
  sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
  sample/src/main/java/com/chuckerteam/chucker/sample/PokemonProtoBodyDecoder.kt
  sample/src/main/proto/com/chuckerteam/chucker/sample/pokemon.proto
Labels: enhancement

#562 Fix UI for emtpy body in request/response
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
Labels: bug

#566 Add reviewers for Github Actions updates PRs
  .github/dependabot.yml
Labels: infra

#569 Display processed encoded bodies
  library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/RequestProcessor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ResponseProcessor.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/TransactionDetailsSharable.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/data/entity/TransactionTestUtils.kt
  library/src/test/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
  library/src/test/java/com/chuckerteam/chucker/util/TestTransactionFactory.kt
Labels: bug
