Repository ChuckerTeam/chucker, pull requests merged in 2021-06, with the labels that each got.

#637 Update 3.5.0
  .github/workflows/auto_rebase.yaml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/pre-merge.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/publish-snapshot.yaml
  README.md
  build.gradle
  gradle.properties
  gradle/gradle-mvn-push.gradle
  gradle/kotlin-static-analysis.gradle
  gradle/wrapper/gradle-wrapper.properties
  library-no-op/build.gradle
  library-no-op/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
  library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
  library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library-no-op/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
  library/build.gradle
  library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
  library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
  library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
  library/src/main/java/com/chuckerteam/chucker/internal/data/model/DialogData.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/ContextExt.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
  library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
  library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
  library/src/main/res/layout/chucker_fragment_transaction_payload.xml
  library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
  library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTupleTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/FormattedUrlTest.kt
  library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
  sample/build.gradle
  sample/src/debug/AndroidManifest.xml
Labels: enhancement

#638 Update readme and change list
  CHANGELOG.md
  README.md
Labels: documentation

#641 Setup automatic repo closure
  .github/workflows/close-and-release-repository.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/publish-snapshot.yaml
  build.gradle
Labels: infra
